### ISSUE TITLE
Test reporter is not correctly delineating test cases in a single class

### ISSUE THREAD

**Issue by DanielJette** [ndtp/android-testify#108]
**Describe the bug**

The Reporter is not correctly delineating test cases in a single class.

This issue relates to:
- [x] The Kotlin library
- [ ] The Gradle plugin
- [ ] The IntelliJ Platform plugin
- [ ] The sample code
- [ ] The documentation

**To Reproduce**

1. Run ClientDetailsViewScreenshotTest from the Sample

Result:

```yml
---
- session: 0c15cf74-1040
- date: 2023-01-02@16:52:30
- failed: 0
- passed: 2
- total: 2
- tests:
    - test:
        name: default
        class: ClientDetailsViewScreenshotTest
        package: dev.testify.sample.clients.details
        baseline_image: assets/screenshots/29-1080x2220@440dp-en_US/default.png
        test_image: /data/user/0/dev.testify.sample/app_images/screenshots/29-1080x2220@440dp-en_US/ClientDetailsViewScreenshotTest_default.png
        status: PASS
        name: usingLayoutResName
        class: ClientDetailsViewScreenshotTest
        package: dev.testify.sample.clients.details
        baseline_image: assets/screenshots/29-1080x2220@440dp-en_US/usingLayoutResName.png
        test_image: /data/user/0/dev.testify.sample/app_images/screenshots/29-1080x2220@440dp-en_US/ClientDetailsViewScreenshotTest_usingLayoutResName.png
        status: PASS
```

**Expected behavior**

Note the duplicate test information under a single `-test` entry.
